import js from "@eslint/js";
import prettier from "eslint-config-prettier";

export default [
    js.configs.recommended,
    prettier,
    {
        languageOptions: {
            ecmaVersion: 2022,
            sourceType: "module",
            globals: {
                window: "readonly",
                document: "readonly",
                navigator: "readonly",
                console: "readonly",
                setTimeout: "readonly",
                setInterval: "readonly",
                clearTimeout: "readonly",
                clearInterval: "readonly",
                fetch: "readonly",
                URL: "readonly",
                Blob: "readonly",
                performance: "readonly",
                THREE: "readonly",
                __log: "readonly",
                __logPaused: "readonly",
                __vrActive: "readonly",
                __logBuffer: "readonly",
                __MAX_LOG_LINES: "readonly",
                __logFreeze: "readonly",
                __logResume: "readonly",
                __onExitPCMode: "readonly",
                Image: "readonly",
                OfflineAudioContext: "readonly",
                AudioContext: "readonly",
                HTMLElement: "readonly",
                XMLHttpRequest: "readonly",
            },
        },
        rules: {
            "no-unused-vars": ["warn", { argsIgnorePattern: "^_" }],
            "no-console": ["warn", { allow: ["warn", "error"] }],
            "prefer-const": "warn",
            "no-var": "warn",
            "eqeqeq": ["warn", "smart"],
            "no-empty": ["warn", { "allowEmptyCatchBlocks": true }],
        },
    },
    {
        ignores: [
            "node_modules/",
            "android/",
            "pico-vr-app/",
            "github-pages/",
            "web/",
            "three.module.js",
            "GLTFLoader.js",
            "BufferGeometryUtils.js",
            "jsm/",
            "draco/",
            "Model_Copy/",
        ],
    },
];